/*
 * rfm69ModemSettings.h
 *
 *  Created on: 20.11.2016
 *      Author: flo
 */

#ifndef SRC_RFM69_RFM69MODEMSETTINGS_H_
#define SRC_RFM69_RFM69MODEMSETTINGS_H_

#include <stdint.h>


#define CONFIG_FSK (REG_DATA_MODUL_DATAMODE_PKT | REG_DATA_MODUL_MODULATION_TYPE_FSK | REG_DATA_MODUL_MODULATION_SHAPING_NO_SHAPING)
#define CONFIG_GFSK (REG_DATA_MODUL_DATAMODE_PKT | REG_DATA_MODUL_MODULATION_TYPE_FSK | REG_DATA_MODUL_MODULATION_SHAPING_GAUSS_BT1_0)
#define CONFIG_OOK (REG_DATA_MODUL_DATAMODE_PKT | REG_DATA_MODUL_MODULATION_TYPE_OOK | REG_DATA_MODUL_MODULATION_SHAPING_NO_SHAPING)

#define CONFIG_NOWHITE (REG_PACKET_CONFIG1_PACKET_FORMAT_VARLEN | REG_PACKET_CONFIG1_DC_FREE_NONE | REG_PACKET_CONFIG1_CRC_ON | REG_PACKET_CONFIG1_ADDR_FILTER_NODE_OR_BRDCAST_ADDR)
#define CONFIG_WHITE (REG_PACKET_CONFIG1_PACKET_FORMAT_VARLEN | REG_PACKET_CONFIG1_DC_FREE_WHITENING | REG_PACKET_CONFIG1_CRC_ON | REG_PACKET_CONFIG1_ADDR_FILTER_NODE_OR_BRDCAST_ADDR)

typedef struct
{
	uint8_t dataModule;
	uint16_t bitrate;
	uint16_t fdev;
	uint8_t rxBw;
	uint8_t afcBw;
	uint8_t packetConfig1;
}RFM69MODEMPARMS_t;

extern const RFM69MODEMPARMS_t MODEM_CONFIG_TABLE[];

#endif /* SRC_RFM69_RFM69MODEMSETTINGS_H_ */
